<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Login to continue_landing-page-input-info_1_2_3_4_5_6_7_8_9_10_11_12_13_14_15_16_17</name>
   <tag></tag>
   <elementGuidId>cf3b8706-9f6c-4fab-adbc-4f55d524c163</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='nguyenvanmuoi@gmai']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.landing-page-input-info</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Enter your email&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e218a4a9-2e08-40f1-a424-ebe0024cdc02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>59fe43cf-9d10-4a15-a6b3-6da5ff965f5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter your email</value>
      <webElementGuid>e39cb933-e108-4369-bab7-fc6eb5b81fde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>landing-page-input-info</value>
      <webElementGuid>cfa060c3-1f51-4652-bcb1-718eecf8f837</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>nguyenvanmuoi@gmai</value>
      <webElementGuid>a4979782-fb48-498d-93b3-733adb3f0f92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;landing-page-login-section&quot;)/form[1]/div[@class=&quot;landing-page-input-container&quot;]/input[@class=&quot;landing-page-input-info&quot;]</value>
      <webElementGuid>971320ed-9d7d-4813-8535-3c8f7b49148f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='nguyenvanmuoi@gmai']</value>
      <webElementGuid>acc0d177-fd0f-42f2-b8c8-6baf15619f41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='landing-page-login-section']/form/div/input</value>
      <webElementGuid>40ae9310-9a76-4486-a053-a3f9785bc5de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>d93e1f8c-fb39-460f-a320-a8d131246dff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @placeholder = 'Enter your email']</value>
      <webElementGuid>c80cfa38-a8dd-4b62-8e76-2a4708345e27</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
